### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by astroanu**

### CODE REVIEW

**Comment by stephenmathieson** [comment]
Hey there! I'm not actively maintaining this anymore. I've invited you to the repository (feel free to do whatever you want with it), and if you provide me your npm username, I can give you access there too.

**Comment by astroanu** [comment]
Cool. I'm using this in couple of my projects. And my CI keeps saying this package has no license. :) Could you please approve this PR?. thanks

**Comment by stephenmathieson** [comment]
If you accept the invitation, you can do it yourself ;)

**Comment by astroanu** [comment]
haha, i somehow missed that email . thanks.

**Pull request merged**
